server:
  port: 8080
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/unittesting"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
